# Dockerfile_LS
ARG STACK_VERSION

FROM docker.elastic.co/logstash/logstash:${STACK_VERSION}

# 작업 디렉토리 설정
WORKDIR /usr/share/logstash

# 기본 패키지 업데이트 및 wget 설치 (루트 권한으로 실행)
USER root
RUN apt-get update && apt-get install -y wget

# MariaDB JDBC 드라이버 다운로드
RUN wget https://dlm.mariadb.com/3852266/Connectors/java/connector-java-3.4.1/mariadb-java-client-3.4.1.jar -P /lib/jars/

# Logstash 설정 파일 복사
COPY ./logstash.conf /usr/share/logstash/pipeline/logstash.conf

# 권한 설정 (JDBC 드라이버)
RUN chmod 644 /lib/jars/mariadb-java-client-3.4.1.jar

# Logstash 실행 명령
CMD ["logstash", "-f", "/usr/share/logstash/pipeline/logstash.conf"]
